config:
subcomponents:
  prometheus-to-azure-monitor-pull:
    config:
      cmd: "pull"
      image:
        repository: "mtarng/prom2azure"
        tag: "v0.1"
      # pull: TBD
        # metric:
          # configFile: # Json config
