config:
subcomponents:
  prometheus-to-azure-monitor-pull:
    config:
      cmd: pull
      image:
        repository: mtarng/prom2azure
        tag: v0.1
      env:
        azure_resoureid: "/subscriptions/<SubscriptionID>/resourcegroups/<ResourceGroup>/providers/Microsoft.ContainerService/managedClusters/mtarngAKSCluster"
        azure_monitor_region: "westus2"
        azure_ad_clientid: "<Azure AD Client ID>"
        azure_ad_client_secret: <Azure AD Client Secret>
        azure_ad_tenantid: "<Azure Tenant ID>"
